CREATE DATABASE StudyManagementApp
GO

USE StudyManagementApp
GO

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(100) PRIMARY KEY,
	PASSWORD VARCHAR(100)
)
GO

ALTER TABLE ACCOUNT ADD EMAIL VARCHAR(100)
GO

-- User Configuration Record
CREATE TABLE USERCONFIG
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	USERNAME VARCHAR(100),
	THEME BIT,
	BACKGROUND_RUNNING_ENABLE BIT,
	STARTUP_ENABLE BIT
)
GO

ALTER TABLE USERCONFIG ADD CONSTRAINT FK_USERCONFIG FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME)
GO

CREATE PROC USP_Login
@userName NVARCHAR(100), @passWord NVARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND PASSWORD = @passWord
END
GO

CREATE PROC USP_Signup
@userName NVARCHAR(100), @passWord NVARCHAR(100), @email VARCHAR(100)
AS
BEGIN
	INSERT INTO ACCOUNT(USERNAME, PASSWORD, EMAIL) VALUES (@userName, @passWord, @email)
END
GO

CREATE PROC USP_ChangePassword
@username NVARCHAR(100), @newPassowrd NVARCHAR(100)
AS
BEGIN
	UPDATE ACCOUNT
	SET PASSWORD=@newPassowrd
	WHERE USERNAME=@username
END
GO

CREATE PROC USP_VerifyUserExist
@userName NVARCHAR(100)
AS
BEGIN
	SELECT USERNAME FROM ACCOUNT WHERE USERNAME = @userName
END
GO

CREATE PROC USP_VerifyEmailExist
@email VARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE EMAIL = @email
END
GO

CREATE PROC USP_EmailOfEachUser
@userName VARCHAR(100), @email VARCHAR(100)
AS
BEGIN
	SELECT * FROM ACCOUNT WHERE USERNAME = @userName AND EMAIL = @email
END
GO

-- USERCONFIG'S PROCEDURE
CREATE PROC InsertUserConfig
@username VARCHAR(100), @theme bit, @background bit, @startup bit
AS
BEGIN
	INSERT INTO USERCONFIG(USERNAME, THEME, BACKGROUND_RUNNING_ENABLE, STARTUP_ENABLE)
		VALUES (@username, @theme, @background, @startup)
END
GO

CREATE PROC GetUserConfig
@username VARCHAR(100)
AS
BEGIN
	SELECT *
	FROM USERCONFIG
	WHERE USERNAME=@username
END
GO

CREATE PROC UpdateUserConfig
@username VARCHAR(100), @theme bit, @background bit, @startup bit
AS
BEGIN
	UPDATE USERCONFIG
	SET THEME=@theme, BACKGROUND_RUNNING_ENABLE=@background, STARTUP_ENABLE=@startup
	WHERE USERNAME=@username
END
GO

CREATE TRIGGER TRG_ACCOUNT_INS ON ACCOUNT
FOR INSERT
AS
BEGIN
	DECLARE @username VARCHAR(100)

	SELECT @username=USERNAME
	FROM INSERTED

	EXEC InsertUserConfig @username, 'false', 'false', 'false'
END
GO

--CREATE PROC USP_GetAccountByUserName
--@userName NVARCHAR(100)
--AS
--BEGIN
--	SELECT * FROM ACCOUNT WHERE USERNAME = @userName
--END
--GO

--EXEC USP_GetAccountByUserName @userName = N'staff'

--SELECT * FROM ACCOUNT WHERE USERNAME = 'staff' AND PASSWORD = '123'
--GO

