USE StudyManagementApp
Go

CREATE TABLE NOTES
(
	PK_NOTES VARCHAR(100),
	USERNAME VARCHAR(100),
	DATETIMECREATE DATETIME,
	TITLE NVARCHAR(50),
	CONTENT NVARCHAR(1000),
	COLOR_ID VARCHAR(7)

	CONSTRAINT PKey_NOTES PRIMARY KEY (PK_NOTES)
)
Go

ALTER TABLE NOTES ADD CONSTRAINT FK_NOTES_ACCOUNT FOREIGN KEY (USERNAME) REFERENCES ACCOUNT(USERNAME);
Go

CREATE PROC ADD_NOTEITEM
	@pk_Notes VARCHAR(100),
	@userName NVARCHAR(100),
	@datetimeCreate DATETIME,
	@title NVARCHAR(50),
	@content NVARCHAR(1000),
	@color_id VARCHAR(7)
AS
BEGIN
	INSERT INTO NOTES VALUES (@pk_Notes , @userName , @datetimeCreate , @title , @content , @color_id )
END
GO

CREATE PROC LOAD_ALLNOTEITEM
@userName NVARCHAR(100)
AS
BEGIN
	SELECT * FROM NOTES WHERE USERNAME = @userName ORDER BY DATETIMECREATE;
END
GO

CREATE PROC UPDATE_NOTEITEM
@pk_notes VARCHAR(100), @title NVARCHAR(50), @content NVARCHAR(1000), @color_id VARCHAR(7)
AS
BEGIN
	UPDATE NOTES
	SET TITLE = @title, CONTENT = @content, COLOR_ID = @color_id
	WHERE PK_NOTES = @pk_notes
END
GO

CREATE PROC DELETE_NOTEITEM
@pk_notes VARCHAR(100)
AS
BEGIN
	DELETE FROM NOTES
	WHERE PK_NOTES = @pk_notes
END
GO